version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/dev/php/Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./symfony:/app/public
      - ./docker/dev/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/dev/php/php.ini:/usr/local/etc/php/php.ini