version: '3.3'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/prod/php/Dockerfile
    restart: always
    environment:
      FRANKENPHP_CONFIG: "worker /app/public/public/index.php"
      APP_RUNTIME: Runtime\FrankenPhpSymfony\Runtime
      MAX_REQUESTS: 10
    ports:
      - "8089:80"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.olympics.rule=Host(`olympics.lucas-trebouet.fr`)"
      - "traefik.http.routers.olympics.entrypoints=websecure"

networks:
  web:
    external: true