version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/dev/php/Dockerfile
    restart: always
    environment:
      FRANKENPHP_CONFIG: "worker /app/public/public/index.php"
      APP_RUNTIME: Runtime\FrankenPhpSymfony\Runtime
      MAX_REQUESTS: 10
    ports:
      - "80:80"
    volumes:
      - ./symfony:/app/public
      - ./docker/dev/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/dev/php/php.ini:/usr/local/etc/php/php.ini